### ISSUE TITLE
Collectors may timeout with STS Expiry Error

### ISSUE THREAD

**Issue by TheM0ng00se** [RiotGames/cloud-inquisitor#162]
During collection, we may sometimes see 

botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the DescribeTrails operation: The security token included in the request is expired

This can happen as retries have a incremental backoff feature and the session lasts greater than the AssumRole Duration (def: 3600s)

**Comment by bunjiboys** [comment]
I don't really think theres anything to be done here. This should only ever be triggered in the event of another bug causing an auditor / collector to run for more than an hour, at which point that plugin should be fixed so that it doesn't hit the exponential backoff on retried API calls and/or do smaller batches of work.
